# Configuration Render.com
services:
    - type: web
      name: symfony-app
      env: docker
      dockerfilePath: ./Dockerfile
      plan: starter
      region: frankfurt
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            generateValue: true
          - key: DATABASE_URL
            fromDatabase:
                name: symfony-db
                property: connectionString
          - key: MESSENGER_TRANSPORT_DSN
            value: doctrine://default?auto_setup=0
          - key: MAILER_DSN
            value: null://null

databases:
    - name: symfony-db
      plan: starter
      databaseName: symfony
      region: frankfurt
